/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const MiniatureModel = (props) => {
   
  const { nodes, materials } = useGLTF("/MyBedRoom2.glb");
  
  return (
    <group {...props} dispose={null} position={[0,-1,0]} rotation={[Math.PI / 12, -Math.PI / 4, 0]}>
      <group position={[-0.79, 0.468, -0.373]} scale={[0.181, 0.022, 0.573]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_2.geometry}
          material={materials["Blue Drawer"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_3.geometry}
          material={materials["Maroon Drawer"]}
        />
      </group>
      <group
        position={[0.309, 0.509, -0.801]}
        rotation={[-Math.PI, 0.37, -Math.PI]}
        scale={[0.045, 0.009, 0.078]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_1.geometry}
          material={materials["Book Blue"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_2.geometry}
          material={materials.White}
        />
      </group>
      <group
        position={[0.309, 0.541, -0.801]}
        rotation={[-Math.PI, 0.51, -Math.PI]}
        scale={[0.045, 0.009, 0.078]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_1.geometry}
          material={materials["Book Green"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_2.geometry}
          material={materials.White}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pencil_Holder.geometry}
        material={materials["Metal Mesh Grill"]}
        position={[0.15, 0.539, -0.831]}
        scale={[0.036, 0.042, 0.036]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pencil_4.geometry}
        material={nodes.Pencil_4.material}
        position={[0.166, 0.575, -0.817]}
        rotation={[0.209, 0, -0.191]}
        scale={[0.091, 0.057, 0.096]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pencil_3.geometry}
        material={nodes.Pencil_3.material}
        position={[0.171, 0.577, -0.837]}
        rotation={[0.259, 0.626, -0.345]}
        scale={[0.095, 0.059, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pencil_2.geometry}
        material={nodes.Pencil_2.material}
        position={[0.13, 0.574, -0.835]}
        rotation={[2.871, -0.681, 2.778]}
        scale={[0.088, 0.055, 0.093]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pencil.geometry}
        material={nodes.Pencil.material}
        position={[0.149, 0.575, -0.808]}
        rotation={[0.246, -0.82, 0.039]}
        scale={[0.084, 0.052, 0.089]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wifi_Router.geometry}
        material={materials.White}
        position={[-0.798, 0.503, -0.346]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.046, -0.011, -0.074]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CPU.geometry}
        material={materials["Material.004"]}
        position={[-0.716, 0.206, -0.399]}
        rotation={[0, 0.637, 0]}
        scale={[0.07, 0.14, 0.18]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Handle.geometry}
        material={nodes.Handle.material}
        position={[-0.614, 0.24, -0.092]}
        rotation={[1.548, 0, 0]}
        scale={[0.01, 0.027, 0.027]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Antenna.geometry}
        material={materials.White}
        position={[-0.847, 0.534, -0.404]}
        scale={[0.065, 0.04, 0.065]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Handle001.geometry}
        material={nodes.Handle001.material}
        position={[-0.614, 0.69, 0.804]}
        rotation={[1.548, 0, 0]}
        scale={[0.01, 0.027, 0.027]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Handle002.geometry}
        material={nodes.Handle002.material}
        position={[-0.614, 0.256, 0.657]}
        rotation={[1.548, 0, 0]}
        scale={[0.01, 0.027, 0.027]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Handle003.geometry}
        material={nodes.Handle003.material}
        position={[-0.614, 0.256, 0.542]}
        rotation={[1.548, 0, 0]}
        scale={[0.01, 0.027, 0.027]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Handle004.geometry}
        material={nodes.Handle004.material}
        position={[-0.614, 0.399, 0.805]}
        rotation={[-0.015, 0.098, 0.006]}
        scale={[0.01, 0.027, 0.027]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Handle005.geometry}
        material={nodes.Handle005.material}
        position={[-0.614, 0.399, 0.388]}
        rotation={[-0.015, 0.098, 0.006]}
        scale={[0.01, 0.027, 0.027]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Handle006.geometry}
        material={nodes.Handle006.material}
        position={[-0.617, 0.993, 0.641]}
        rotation={[1.548, 0, 0]}
        scale={[0.01, 0.027, 0.027]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Handle007.geometry}
        material={nodes.Handle007.material}
        position={[-0.617, 0.993, 0.565]}
        rotation={[1.548, 0, 0]}
        scale={[0.01, 0.027, 0.027]}
      />
      <group
        position={[-0.558, 0.489, -0.617]}
        rotation={[0, -1.048, 0]}
        scale={0.577}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011.geometry}
          material={materials["keyboard key.001"]}
          position={[-0.058, 0.023, -0.032]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012.geometry}
          material={materials["keyboard key.001"]}
          position={[-0.056, 0.023, 0.232]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={materials["keyboard key.001"]}
          position={[-0.058, 0.023, 0.199]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014.geometry}
          material={materials["keyboard key.001"]}
          position={[-0.014, 0.023, 0.201]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015.geometry}
          material={materials["keyboard key.001"]}
          position={[0.007, 0.023, 0.201]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016.geometry}
          material={materials["keyboard key.001"]}
          position={[0.029, 0.023, 0.199]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017.geometry}
          material={materials["keyboard key.001"]}
          position={[0.05, 0.023, 0.201]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018.geometry}
          material={materials["keyboard key.001"]}
          position={[0.05, 0.023, 0.173]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019.geometry}
          material={materials["keyboard key.001"]}
          position={[0.05, 0.023, 0.145]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020.geometry}
          material={materials["keyboard key.001"]}
          position={[0.05, 0.023, -0.005]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021.geometry}
          material={materials["keyboard key.001"]}
          position={[0.05, 0.023, -0.033]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022.geometry}
          material={materials["keyboard key.001"]}
          position={[0.05, 0.023, -0.061]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023.geometry}
          material={materials["keyboard key.001"]}
          position={[0.05, 0.023, -0.088]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube024.geometry}
          material={materials["keyboard key.001"]}
          position={[0.028, 0.023, -0.088]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube025.geometry}
          material={materials["keyboard key.001"]}
          position={[-0.035, 0.023, -0.077]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026.geometry}
          material={materials["keyboard key.001"]}
          position={[-0.058, 0.023, -0.124]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027.geometry}
          material={materials["keyboard key.001"]}
          position={[-0.036, 0.023, -0.124]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028.geometry}
          material={materials["keyboard key.001"]}
          position={[-0.016, 0.023, -0.124]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube029.geometry}
          material={materials["keyboard key.001"]}
          position={[0.05, 0.023, -0.126]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube030.geometry}
          material={materials["keyboard key.001"]}
          position={[0.029, 0.023, -0.146]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube031.geometry}
          material={materials["keyboard key.001"]}
          position={[-0.036, 0.023, -0.197]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube032.geometry}
          material={materials["keyboard key.001"]}
          position={[0.05, 0.023, 0.088]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033.geometry}
          material={materials["keyboard key.001"]}
          position={[-0.015, 0.023, -0.087]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube034.geometry}
          material={materials["keyboard key.001"]}
          position={[0.048, 0.023, -0.197]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035.geometry}
          material={materials["keyboard key.001"]}
          position={[0.048, 0.023, -0.238]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube036.geometry}
          material={materials["keyboard key.001"]}
          position={[0.03, 0.023, -0.259]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube037.geometry}
          material={materials["keyboard key.001"]}
          position={[-0.012, 0.023, -0.259]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube038.geometry}
          material={materials["keyboard key.001"]}
          position={[-0.036, 0.023, -0.259]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube039.geometry}
          material={materials["keyboard key.001"]}
          position={[-0.061, 0.014, -0.197]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube040.geometry}
          material={materials["keyboard key.001"]}
          position={[-0.093, 0.014, -0.214]}
        />
        <group position={[-0.092, -0.002, -0.149]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube048_1.geometry}
            material={materials["keyboard key.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube048_2.geometry}
            material={materials["keyboard.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube048_3.geometry}
            material={materials["rubber.002"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube042.geometry}
          material={materials["keyboard key.001"]}
          position={[-0.058, 0.023, 0.067]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube043.geometry}
          material={materials["keyboard key.001"]}
          position={[-0.058, 0.023, 0.164]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube044.geometry}
          material={materials["keyboard key.001"]}
          position={[-0.035, 0.023, 0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube045.geometry}
          material={materials["keyboard key.001"]}
          position={[0.029, 0.023, 0.176]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube046.geometry}
          material={materials["keyboard key.001"]}
          position={[0.007, 0.023, 0.165]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube047.geometry}
          material={materials["keyboard key.001"]}
          position={[-0.015, 0.023, 0.171]}
        />
        <group position={[-0.092, 0.016, -0.159]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder014.geometry}
            material={materials["LIGHT on.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder014_1.geometry}
            material={materials["LIGHT off.001"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009.geometry}
          material={materials["keyboard key.001"]}
          position={[-0.092, 0.015, -0.103]}
        />
      </group>
      <group
        position={[-0.683, 0.496, -0.795]}
        rotation={[0, -1.088, 0]}
        scale={0.076}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_1.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_2.geometry}
          material={materials.Screen}
        />
      </group>
      <group
        position={[-0.836, 1.003, -0.173]}
        rotation={[0, 0.007, 0]}
        scale={[0.127, 0.136, 0.374]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_1.geometry}
          material={materials["LIGHT off.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_2.geometry}
          material={materials["Maroon Drawer"]}
        />
      </group>
      <group position={[0.747, 0.041, -0.737]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["Material.003"]}
          position={[0, 0.067, 0]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002.geometry}
          material={materials["Material.002"]}
          position={[0, 0.078, 0]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003.geometry}
          material={materials["Material.002"]}
          position={[0.032, 0.078, 0.006]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004.geometry}
          material={materials["Material.002"]}
          position={[0.006, 0.083, 0.042]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005.geometry}
          material={materials["Material.002"]}
          position={[0, 0.079, 0]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006.geometry}
          material={materials["Material.002"]}
          position={[0, 0.079, 0]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007.geometry}
          material={materials["Material.002"]}
          position={[0, 0.117, 0]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008.geometry}
          material={materials["Material.002"]}
          position={[0, 0.079, 0]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009.geometry}
          material={materials["Material.002"]}
          position={[0, 0.079, 0.035]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010.geometry}
          material={materials["Material.002"]}
          position={[0, 0.079, 0]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011.geometry}
          material={materials["Material.002"]}
          position={[0, 0.079, 0]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012.geometry}
          material={materials["Material.002"]}
          position={[0, 0.079, 0]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013.geometry}
          material={materials["Material.002"]}
          position={[-0.036, 0.07, -0.017]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials["Material.002"]}
          position={[0, 0.079, 0]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015.geometry}
          material={materials["Material.002"]}
          position={[0, 0.079, 0]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016.geometry}
          material={materials["Material.002"]}
          position={[0, 0.079, 0]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017.geometry}
          material={materials["Material.002"]}
          position={[0, 0.079, 0]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018.geometry}
          material={materials["Material.002"]}
          position={[0, 0.079, 0]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane019.geometry}
          material={materials["Material.002"]}
          position={[0, 0.079, 0]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane020.geometry}
          material={materials["Material.002"]}
          position={[0.003, 0.093, 0.009]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane021.geometry}
          material={materials["Material.002"]}
          position={[0, 0.113, 0.013]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane022.geometry}
          material={materials["Material.002"]}
          position={[-0.026, 0.106, -0.03]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane023.geometry}
          material={materials["Material.002"]}
          position={[0, 0.119, 0]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane024.geometry}
          material={materials["Material.002"]}
          position={[0, 0.079, 0]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane025.geometry}
          material={materials["Material.002"]}
          position={[0.019, 0.078, -0.028]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane026.geometry}
          material={materials["Material.001"]}
          position={[0, 0.116, 0]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane027.geometry}
          material={materials["Material.002"]}
          position={[-0.025, 0.084, -0.013]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane028.geometry}
          material={materials["Material.002"]}
          position={[-0.025, 0.077, -0.005]}
          rotation={[0, 1.571, 0]}
        />
      </group>
      <group
        position={[-0.083, 0.034, -0.17]}
        rotation={[0, -0.632, 0]}
        scale={0.683}
      >
        <group
          position={[0.168, 0.359, -0.064]}
          rotation={[-0.12, 0.051, -0.401]}
          scale={0.255}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012_1.geometry}
            material={materials["black skin"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012_2.geometry}
            material={materials.outline}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials["black skin"]}
          position={[-0.008, 0.571, -0.129]}
          rotation={[-0.208, 0, 0]}
          scale={[0.119, 0.115, 0.093]}
        />
        <group
          position={[0.033, 0.079, 0.051]}
          rotation={[0, -0.712, 0]}
          scale={[0.02, 0.02, 0.018]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_1.geometry}
            material={materials["black plactic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_2.geometry}
            material={materials.outline}
          />
        </group>
        <group
          position={[0.039, 0.078, -0.005]}
          rotation={[0, 0.389, 0]}
          scale={[0.02, 0.02, 0.018]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_1.geometry}
            material={materials["black plactic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_2.geometry}
            material={materials.outline}
          />
        </group>
        <group
          position={[-0.051, 0.078, 0]}
          rotation={[Math.PI, 0.328, 0]}
          scale={[-0.02, -0.02, -0.018]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_1.geometry}
            material={materials["black plactic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_2.geometry}
            material={materials.outline}
          />
        </group>
        <group
          position={[-0.006, 0.078, -0.036]}
          rotation={[-Math.PI, 1.571, 0]}
          scale={[-0.02, -0.02, -0.018]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_1.geometry}
            material={materials["black plactic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_2.geometry}
            material={materials.outline}
          />
        </group>
        <group
          position={[-0.04, 0.078, 0.054]}
          rotation={[Math.PI, -0.882, Math.PI]}
          scale={[0.02, 0.02, 0.018]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_1.geometry}
            material={materials["black plactic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_2.geometry}
            material={materials.outline}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008.geometry}
          material={materials["black plactic"]}
          position={[-0.005, 0.077, 0.016]}
          rotation={[0, -0.343, 0]}
          scale={[0.061, 0.034, 0.061]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={materials["black plactic"]}
          position={[-0.131, 0.291, 0.074]}
          rotation={[Math.PI, -0.452, Math.PI]}
          scale={[0.36, 0.412, 0.36]}
        />
        <group position={[0, 0.526, 0.045]} scale={[0.154, 0.202, 0.255]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube013_1.geometry}
            material={materials["black skin"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube013_2.geometry}
            material={materials.outline}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials["black plactic"]}
          position={[-0.004, 0.141, 0.015]}
          scale={0.028}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002.geometry}
          material={materials["black plactic"]}
          position={[0.214, 0.018, 0.206]}
          rotation={[-Math.PI / 2, 0, -0.73]}
          scale={-0.283}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={materials["black plactic"]}
          position={[0.265, 0.016, -0.098]}
          rotation={[-Math.PI / 2, 0, 0.435]}
          scale={-0.283}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004.geometry}
          material={materials["black plactic"]}
          position={[-0.006, 0.016, -0.276]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={-0.283}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005.geometry}
          material={materials["black plactic"]}
          position={[-0.275, 0.016, -0.077]}
          rotation={[Math.PI / 2, 0, 0.315]}
          scale={0.283}
        />
        <group position={[0.245, 0.34, 0.148]} scale={[0.012, 0.006, 0.017]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder006_1.geometry}
            material={materials["black skin"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder006_2.geometry}
            material={materials.metal}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007.geometry}
          material={materials["black plactic"]}
          position={[-0.191, 0.016, 0.238]}
          rotation={[Math.PI / 2, 0, -0.876]}
          scale={0.283}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object.geometry}
          material={materials["black plactic"]}
          position={[-0.004, 0.275, 0.178]}
          rotation={[3.129, 0, Math.PI]}
          scale={[1.063, 0.907, 1.004]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object001.geometry}
          material={materials["black plactic"]}
          position={[-0.004, 0.313, 0.117]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[1.637, 1.063, 1.063]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane029.geometry}
          material={materials.outline}
          position={[-0.005, 0.883, -0.189]}
          rotation={[1.381, 0, 0]}
          scale={[0.118, 0.087, 0.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane030.geometry}
          material={materials["black skin"]}
          position={[-0.005, 0.885, -0.24]}
          rotation={[1.502, 0, 0]}
          scale={0.008}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane031.geometry}
          material={materials.outline}
          position={[0.07, 0.585, -0.074]}
          rotation={[1.293, 0, 0]}
          scale={[0.019, 0.079, 0.079]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane032.geometry}
          material={materials["Material.004"]}
          position={[0.196, 0.356, -0.114]}
          rotation={[-0.119, 0.179, -1.549]}
          scale={0.013}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane033.geometry}
          material={materials["Material.004"]}
          position={[-0.19, 0.525, -0.13]}
          rotation={[-0.126, 0.075, -1.481]}
          scale={0.013}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane034.geometry}
          material={materials["Material.004"]}
          position={[0.196, 0.356, -0.114]}
          rotation={[-0.119, 0.179, -1.549]}
          scale={0.013}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane035.geometry}
          material={materials["Material.004"]}
          position={[0.187, 0.356, -0.113]}
          rotation={[-0.119, 0.179, -1.549]}
          scale={0.013}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane036.geometry}
          material={materials["Material.004"]}
          position={[0.187, 0.356, -0.113]}
          rotation={[-0.119, 0.179, -1.549]}
          scale={0.013}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane037.geometry}
          material={materials["Material.004"]}
          position={[0.191, 0.356, -0.113]}
          rotation={[-0.123, 0.177, -1.528]}
          scale={0.013}
        />
        <group position={[0.245, 0.584, 0.166]} scale={[0.169, 0.255, 0.266]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane011_1.geometry}
            material={materials["black skin"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane011_2.geometry}
            material={materials.outline}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane039.geometry}
          material={materials.Material}
          position={[-0.005, 0.883, -0.189]}
          rotation={[1.381, 0, 0]}
          scale={[0.118, 0.087, 0.079]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane040.geometry}
          material={materials["black skin"]}
          position={[0.06, 0.922, -0.221]}
          rotation={[1.525, 0, 0]}
          scale={[0.038, 0.034, 0.038]}
        />
        <group
          position={[-0.006, 0.774, -0.178]}
          rotation={[1.605, 0, 0]}
          scale={[0.132, 0.143, 0.096]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane015_1.geometry}
            material={materials["black skin"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane015_2.geometry}
            material={materials.outline}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text.geometry}
          material={materials.outline}
          position={[-0.051, 1.041, -0.205]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.038}
        />
      </group>
      <group
        position={[-0.34, 0.489, -0.727]}
        rotation={[Math.PI, -0.681, Math.PI]}
      >
        <group position={[0, 0.015, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube014_1.geometry}
            material={materials["Mouse - Shiny Grey"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube014_2.geometry}
            material={materials["Mouse - Mat Grey"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Top.geometry}
          material={materials["Mouse - Mat Grey"]}
          position={[0, 0.024, 0.001]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wheel.geometry}
          material={materials["Mouse - Wheel Grey"]}
          position={[0, 0.02, 0.03]}
          rotation={[1.875, 0, 0]}
        />
      </group>
      <group
        position={[-0.809, 0.987, -0.523]}
        rotation={[0.48, 1.422, -0.482]}
        scale={0.526}
      >
        <group
          position={[-0.388, 0.106, -0.007]}
          rotation={[1.573, -0.45, -1.571]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.365, 0.111, -0.008]}
          rotation={[1.571, -0.427, -1.572]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube016_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube016_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.349, 0.085, 0.008]}
          rotation={[1.57, -0.323, -1.575]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube017_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube017_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.283, 0.1, 0.009]}
          rotation={[1.57, -0.218, -1.573]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube018_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube018_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.294, 0.116, -0.002]}
          rotation={[1.569, -0.22, -1.575]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube019_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube019_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.311, 0.114, -0.005]}
          rotation={[1.57, -0.22, -1.575]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube020_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube020_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.267, 0.099, -0.003]}
          rotation={[1.57, -0.217, -1.574]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube021_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube021_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.143, 0.103, -0.006]}
          rotation={[1.571, -0.2, -1.569]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube021_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube021_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.19, 0.12, -0.005]}
          rotation={[1.572, -0.206, -1.567]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube020_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube020_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.172, 0.122, -0.006]}
          rotation={[1.569, -0.205, -1.569]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube019_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube019_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.161, 0.104, -0.011]}
          rotation={[1.571, -0.204, -1.569]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube018_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube018_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.219, 0.091, -0.002]}
          rotation={[1.571, -0.214, -1.569]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube017_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube017_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.23, 0.123, -0.009]}
          rotation={[1.57, -0.214, -1.572]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube016_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube016_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.248, 0.118, -0.005]}
          rotation={[1.57, -0.215, -1.573]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.126, 0.119, -0.007]}
          rotation={[1.571, -0.201, -1.569]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.108, 0.123, -0.006]}
          rotation={[1.571, -0.201, -1.568]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube016_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube016_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.092, 0.091, -0.004]}
          rotation={[1.571, -0.152, -1.569]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube017_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube017_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.033, 0.105, 0.002]}
          rotation={[1.571, -0.106, -1.569]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube018_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube018_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.045, 0.123, -0.008]}
          rotation={[1.572, -0.106, -1.569]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube019_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube019_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.063, 0.12, -0.005]}
          rotation={[1.57, -0.108, -1.57]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube020_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube020_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.015, 0.104, 0.001]}
          rotation={[1.571, -0.102, -1.571]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube021_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube021_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
      </group>
      <group
        position={[-0.809, 0.987, -0.131]}
        rotation={[0.48, 1.422, -0.482]}
        scale={0.526}
      >
        <group
          position={[-0.388, 0.106, -0.007]}
          rotation={[1.573, -0.45, -1.571]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube022_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube022_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.365, 0.111, -0.008]}
          rotation={[1.571, -0.427, -1.572]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube023_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube023_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.349, 0.085, 0.008]}
          rotation={[1.57, -0.323, -1.575]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube024_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube024_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.283, 0.1, 0.009]}
          rotation={[1.57, -0.218, -1.573]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube025_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube025_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.294, 0.116, -0.002]}
          rotation={[1.569, -0.22, -1.575]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube026_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube026_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.311, 0.114, -0.005]}
          rotation={[1.57, -0.22, -1.575]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube027_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube027_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.267, 0.099, -0.003]}
          rotation={[1.57, -0.217, -1.574]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube028_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube028_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.143, 0.103, -0.006]}
          rotation={[1.571, -0.2, -1.569]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube028_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube028_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.19, 0.12, -0.005]}
          rotation={[1.572, -0.206, -1.567]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube027_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube027_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.172, 0.122, -0.006]}
          rotation={[1.569, -0.205, -1.569]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube026_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube026_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.161, 0.104, -0.011]}
          rotation={[1.571, -0.204, -1.569]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube025_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube025_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.219, 0.091, -0.002]}
          rotation={[1.571, -0.214, -1.569]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube024_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube024_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.23, 0.123, -0.009]}
          rotation={[1.57, -0.214, -1.572]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube023_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube023_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.248, 0.118, -0.005]}
          rotation={[1.57, -0.215, -1.573]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube022_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube022_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.126, 0.119, -0.007]}
          rotation={[1.571, -0.201, -1.569]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube022_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube022_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.108, 0.123, -0.006]}
          rotation={[1.571, -0.201, -1.568]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube023_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube023_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.092, 0.091, -0.004]}
          rotation={[1.571, -0.152, -1.569]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube024_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube024_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.033, 0.105, 0.002]}
          rotation={[1.571, -0.106, -1.569]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube025_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube025_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.045, 0.123, -0.008]}
          rotation={[1.572, -0.106, -1.569]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube026_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube026_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.063, 0.12, -0.005]}
          rotation={[1.57, -0.108, -1.57]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube027_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube027_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.015, 0.104, 0.001]}
          rotation={[1.571, -0.102, -1.571]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube028_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube028_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
      </group>
      <group
        position={[-0.809, 0.875, 0.005]}
        rotation={[0.547, 1.422, -0.482]}
        scale={0.407}
      >
        <group
          position={[-0.388, 0.106, -0.007]}
          rotation={[1.573, -0.45, -1.571]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube029_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube029_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.365, 0.111, -0.008]}
          rotation={[1.571, -0.427, -1.572]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube030_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube030_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.349, 0.085, 0.008]}
          rotation={[1.57, -0.323, -1.575]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube031_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube031_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.283, 0.1, 0.009]}
          rotation={[1.57, -0.218, -1.573]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube032_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube032_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.294, 0.116, -0.002]}
          rotation={[1.569, -0.22, -1.575]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube033_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube033_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.311, 0.114, -0.005]}
          rotation={[1.57, -0.22, -1.575]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube034_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube034_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.267, 0.099, -0.003]}
          rotation={[1.57, -0.217, -1.574]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube035_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube035_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.143, 0.103, -0.006]}
          rotation={[1.571, -0.2, -1.569]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube035_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube035_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.19, 0.12, -0.005]}
          rotation={[1.572, -0.206, -1.567]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube034_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube034_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.172, 0.122, -0.006]}
          rotation={[1.569, -0.205, -1.569]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube033_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube033_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.161, 0.104, -0.011]}
          rotation={[1.571, -0.204, -1.569]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube032_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube032_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.219, 0.091, -0.002]}
          rotation={[1.571, -0.214, -1.569]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube031_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube031_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.23, 0.123, -0.009]}
          rotation={[1.57, -0.214, -1.572]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube030_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube030_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.248, 0.118, -0.005]}
          rotation={[1.57, -0.215, -1.573]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube029_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube029_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.126, 0.119, -0.007]}
          rotation={[1.571, -0.201, -1.569]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube029_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube029_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.108, 0.123, -0.006]}
          rotation={[1.571, -0.201, -1.568]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube030_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube030_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.092, 0.091, -0.004]}
          rotation={[1.571, -0.152, -1.569]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube031_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube031_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.033, 0.105, 0.002]}
          rotation={[1.571, -0.106, -1.569]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube032_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube032_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.045, 0.123, -0.008]}
          rotation={[1.572, -0.106, -1.569]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube033_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube033_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.063, 0.12, -0.005]}
          rotation={[1.57, -0.108, -1.57]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube034_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube034_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[-0.015, 0.104, 0.001]}
          rotation={[1.571, -0.102, -1.571]}
          scale={1.045}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube035_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube035_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
      </group>
      <group position={[0.194, 0.489, -0.635]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.main_bottle.geometry}
          material={materials["Material.004"]}
          position={[0.131, 0.102, 0.222]}
          scale={0.636}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_1.geometry}
        material={materials.MarbleLight}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_2.geometry}
        material={materials["Book Blue"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_3.geometry}
        material={materials.Glass}
      />
    </group>
  );
}

useGLTF.preload("/src/assets/MyBedRoom2.glb");

export default MiniatureModel
